
version: '3.8'

services:
  symptom-checker-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - Langfuse_secretkey=${Langfuse_secretkey}
      - Langfuse_publickey=${Langfuse_publickey}
      - Groq_key=${Groq_key}
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  symptom-checker-ui:
    build: .
    ports:
      - "5000:5000"
    environment:
      - Langfuse_secretkey=${Langfuse_secretkey}
      - Langfuse_publickey=${Langfuse_publickey}
      - Groq_key=${Groq_key}
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=5000
